import { EntityExtraction, ForensicCase } from "@shared/api";

export function openPrintableReport({
  forensicCase,
  entities,
  notes,
}: {
  forensicCase: ForensicCase;
  entities: EntityExtraction;
  notes?: string;
}) {
  const win = window.open("", "_blank", "noopener,noreferrer");
  if (!win) return;
  const styles = `
    body { font-family: Inter, ui-sans-serif, system-ui, -apple-system, Segoe UI, Roboto, Helvetica, Arial; padding: 32px; color: #0f172a }
    h1 { font-size: 20px; margin: 0 0 8px; }
    h2 { font-size: 16px; margin: 24px 0 8px; }
    .muted { color: #475569 }
    .card { border: 1px solid #e2e8f0; border-radius: 12px; padding: 16px; }
    .grid { display: grid; grid-template-columns: repeat(2, minmax(0, 1fr)); gap: 12px; }
    ul { margin: 4px 0 0 16px }
    .badge { display:inline-block; padding:2px 8px; border-radius:999px; background:#eef2ff; color:#3730a3; font-weight:600; }
  `;
  const html = `
  <!doctype html>
  <html>
    <head>
      <meta charset="utf-8" />
      <title>Case Report ${forensicCase.id}</title>
      <style>${styles}</style>
    </head>
    <body>
      <h1>ForensiQ Report <span class="badge">${forensicCase.status}</span></h1>
      <div class="muted">Case ${forensicCase.id} • ${new Date(forensicCase.date).toLocaleString()}</div>
      <p>${forensicCase.description}</p>
      <div class="grid">
        <div class="card">
          <h2>Entities</h2>
          <strong>Emails</strong>
          <ul>${entities.emails.map((e) => `<li>${e}</li>`).join("") || "<li>None</li>"}</ul>
          <strong>Crypto</strong>
          <ul>${entities.crypto.map((e) => `<li>${e}</li>`).join("") || "<li>None</li>"}</ul>
          <strong>Phones</strong>
          <ul>${entities.phones.map((e) => `<li>${e}</li>`).join("") || "<li>None</li>"}</ul>
        </div>
        <div class="card">
          <h2>Notes</h2>
          <p class="muted">${notes || "Generated by ForensiQ."}</p>
        </div>
      </div>
      <script>window.onload = () => window.print();</script>
    </body>
  </html>`;
  win.document.write(html);
  win.document.close();
}
